#!/usr/bin/env bash
#
# Copyright 2013 Arjan Scherpenisse
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#	 http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# usage zotonic-migratemodule <directory> ...
#


function do_migrate {
    DIR="$1";
    if [ ! -d $DIR ]; then
        echo "*** $DIR is not a directory" 1>&2
        return
    fi

    BASE=`basename $DIR`
    echo "Migrating $BASE"

    pushd . >/dev/null
    cd $DIR

    if [ -f config ]; then
        # as site
        TYPE=site
    else
        TYPE=module
    fi
    
    if [ ! -f "$BASE.erl" ]; then
        echo "*** $BASE is not a old-style Zotonic module"
        popd >/dev/null
        return
    fi

    mkdir -p src
    mv -v $BASE.erl src/
    for srcdir in controllers actions support filters scomps services validators models; do
        if [ -d $srcdir ]; then
            mv $srcdir src
        fi
    done

    mkdir -p priv
    for srcdir in templates dispatch lib translations; do
        if [ -d $srcdir ]; then
            mv $srcdir priv
        fi
    done

    cat > src/$BASE.app.src <<EOF
{application, $BASE,
 [{description, "The Zotonic $TYPE: $BASE"},
  {vsn, "1"},
  {modules, []},
  {registered, []},
  {env, [{zotonic_type, $TYPE}]},
  {applications, [zotonic]}]}.
EOF
    git add -A .
    
    popd > /dev/null
}

for dir in $@; do
    do_migrate "$dir"
done

